# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.network "public_network", ip: "192.168.1.30", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.box_check_update = false
  config.vm.hostname = "masterk8s"
  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = 2
  end
end
