- hosts: master
  remote_user: vagrant
  become: yes
  become_method: sudo

  tasks:
    - name: initialize the cluster
      shell: kubeadm init  --apiserver-advertise-address=192.168.1.30 --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: centos # Change to the appropriate user
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/centos/.kube/config
        remote_src: yes
        owner: centos # Change to the appropriate user

    - name: install Pod network
      become: yes
      become_user: centos
      shell: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt